// <auto-generated />
using System;
using ClientBarometer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClientBarometer.Migrator.Migrations.ClientBarometerDb
{
    [DbContext(typeof(ClientBarometerDbContext))]
    [Migration("20210822054942_updateSuggestions")]
    partial class updateSuggestions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ClientBarometer.Domain.Models.BarometerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("barometer_values");
                });

            modelBuilder.Entity("ClientBarometer.Domain.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("chats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c43a70b-163c-4457-8cfa-42242bced8fa"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Source = "Telegram",
                            SourceId = "352328891"
                        });
                });

            modelBuilder.Entity("ClientBarometer.Domain.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("Id");

                    b.HasIndex("UserId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("ClientBarometer.Domain.Models.Objection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectionClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("objection");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e880ecc-6bef-49ec-ba7e-383e93f2cd10"),
                            Example = "не вижу интереса в этом продукте",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("928c1c20-ce22-4713-a937-1885b917dfee"),
                            Example = "не интересно",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("0f5051f3-3116-4f99-a166-837ecd42ce29"),
                            Example = "не вижу ничего интересного ",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("0c61d669-5d5a-4fb4-9eda-4d3978c07a14"),
                            Example = "ваш продукт нам не интересен",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("001d8f02-fc76-4666-846b-db08fa8ca5fc"),
                            Example = "не интересно предложение в принципе",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("f66e9b09-7b5a-446f-b8f6-bcf4437e327a"),
                            Example = "не понимаю, как это может быть интересно",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("1e9d5584-8fd3-4828-9a72-22d9f3863a3d"),
                            Example = "мне не интересно",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("a6dfef88-0bfc-4b92-bc7a-13d535381cee"),
                            Example = "нам не интересно это изучать",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("a5d82ebd-2f4c-4574-a981-a8d36cbc96fa"),
                            Example = "мы не заинтересованы в этом",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("941e0b82-1fdb-4fa0-b06a-e10871d2e934"),
                            Example = "простите, не заинтересовало",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("8a5482d3-f558-4185-8917-b255c865117c"),
                            Example = "не заинтересован",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("f9a40399-942b-4bd0-8372-37b561bf9c42"),
                            Example = "мы не видим в этом ничего интересного",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("434819c0-d339-4580-886d-e542a76ce61f"),
                            Example = "ничего интересного в этом не видим",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("03a43ce6-e699-493a-8bdc-d1985fcbb97c"),
                            Example = "не видим в этом ничего интересного",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("e2d984c3-7afa-4dab-a231-226c4b4a2f40"),
                            Example = "ваше предложение просто не интересно",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("72faa124-84aa-4845-92be-9aee1f8893cd"),
                            Example = "просто не интересно",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("3ff87dc1-733b-4f6e-b04b-5534533b60b1"),
                            Example = "у нас другой поставщик услуг",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("39c88153-bd36-4fbf-a0c2-067b8b5ff698"),
                            Example = "у нас другой подрядчик",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("6ecd69e2-b8f1-42a1-a5fd-881695e58086"),
                            Example = "мы пользуемся другим продуктов",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("1f38fd95-6a39-4530-8464-4fca0e9ea9c7"),
                            Example = "нам больше нравится другой товар",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("34aa60ff-77d3-4c04-8826-2854f3d504e3"),
                            Example = "мы уже пользуемся продуктами ваших конкурентов",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("856e1204-289e-401f-a7fc-e9c6586f666b"),
                            Example = "мы уже пользуемся конкурирующими продуктами",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("d7bfb83f-6e6c-4fc6-8a5f-d7f433a7813a"),
                            Example = "мы пользуемся продуктами другой компании",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("a9b5153c-db11-4329-a24c-6ef96fa5fffe"),
                            Example = "у нас есть решение от другого вендора",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("a3040f34-6122-412f-aa15-7a6bec1228bc"),
                            Example = "мы уже приняли о работе с другими",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("df546be7-2e65-4c4e-bac4-9a3c6a6a68be"),
                            Example = "другие участники рынка нам более интересны",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("18bf6915-1e3b-420d-a9c6-473bfab1a2a5"),
                            Example = "уже пользуемся чужими продуктами",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("020c8bc8-17b1-46d7-a9fd-e7e166b6fc20"),
                            Example = "уже пользуемся иными продуктами",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("030878da-daad-424b-811d-234b2b1be584"),
                            Example = "уже пользуемся продуктами других подрядчиков",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("8a9f7059-71a6-48b7-a71d-2a4b9f5d05a6"),
                            Example = "другие поставщики уже работают с нами",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("3ef43977-8f39-4c5b-82b5-83464d537685"),
                            Example = "у нас этим занимаются другие люди",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("b7279c06-b4fd-4938-a2d6-bb40256fae5b"),
                            Example = "другие люди уже покрыли это ",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("daa8e1cf-20af-40e6-a51a-793314c7d235"),
                            Example = "у нас это организовано с другим подрядчиком",
                            ObjectionClass = "Мы работаем с другими"
                        },
                        new
                        {
                            Id = new Guid("c70d0b91-cbfe-4619-96a3-4b0942e4888c"),
                            Example = "у нас и так все есть",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("40ad7631-ff07-411c-9bcd-9793a4206df3"),
                            Example = "у нас и так все нормально",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("e0fddefb-fb2a-4bab-99a3-d4056172eb1c"),
                            Example = "у нас все ок",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("b5803911-de0d-4827-831c-ea06fa646069"),
                            Example = "нам ничего не нужно у нас все нормально",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("c7a8aa34-a6ea-4912-aff1-392e397af2c6"),
                            Example = "нам ничего не нужно у нас все есть",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("1ac4eea1-becb-46b7-b4c3-dd0ef409ceb2"),
                            Example = "все и так хорошо",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("989ab18d-bab5-4379-8627-d735fec89529"),
                            Example = "ничего не надо",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("daaac439-9446-4413-a6d0-76bd23f34afb"),
                            Example = "ничего не надо все и так хорошо",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("0827e416-2b1c-4407-82bf-11627d7aa1fb"),
                            Example = "все и так хорошо ничего не надо",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("5633e57d-d1b2-44a7-a595-21099f630aeb"),
                            Example = "мы ничего не хотим",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("c4dc6783-df0c-4063-a14b-42df7a3185b7"),
                            Example = "не хотим ничего вообще все есть",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("a4724029-d99f-4666-9438-9868e09d21e3"),
                            Example = "у нас все есть ничего не надо",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("41a6b4e4-0a6c-4093-afd4-bb6a5021ac52"),
                            Example = "ничего нам не нужно",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("c8d0d853-5e61-4813-a6d6-993b3755e1b6"),
                            Example = "нет спасибо ничего не нужно",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("f74cff76-df70-4975-a92e-a29dc2066d32"),
                            Example = "спасибо у нас все уже есть не надо ничего",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("c5a2a935-acce-48fa-aa28-a0bf383aa0b5"),
                            Example = "нет не надо ничего все есть",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("37b05188-936b-4965-b83b-d74210016b7c"),
                            Example = "у нас как-то все есть ничего не надо",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("b4773ad3-bbcb-4d12-820f-b7ada430ba6f"),
                            Example = "как-то вышло что все есть не надо спасибо",
                            ObjectionClass = "Нам ничего не нужно/ у нас все есть"
                        },
                        new
                        {
                            Id = new Guid("47bb51b3-0046-4676-b79b-d3324602efc1"),
                            Example = "пришлите пожалуйста информацию",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("75152257-5f33-4048-bca2-0e9e75b26549"),
                            Example = "свяжитесь пожалуйста со мной по скайпу",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("185ede65-c6c0-47da-a74c-9fc1904ba771"),
                            Example = "свяжитесь по почте",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("759cdd54-4dd7-44b7-a1ab-6e7c8b0f2a5d"),
                            Example = "пришлите свое кп",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("1ef2ee11-511e-4ec9-a6d7-a77c36b9820a"),
                            Example = "пришлите информацию на емейл",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("6566dbfd-c522-453d-8ded-c9ce411e324b"),
                            Example = "перешлите информацию",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("22f4ac92-f2e9-4d07-8291-20a7a2322ecd"),
                            Example = "свяжитесь по скайпу",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("8efeb1f9-4d83-40c0-9802-968b53d4213d"),
                            Example = "пришлите информацию сейчас",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("dafe7864-0e51-43e7-a03e-78cb666d4347"),
                            Example = "хочу чтобы вы прислали информацию в письме",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("48c067b5-6349-4b65-9fba-86b069dc292c"),
                            Example = "хочу получить от вас письмо с информацией",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("a2f0d8fd-a82f-4f84-a5b6-ee2280105ac7"),
                            Example = "мне нужно получить от вас информацию по почте",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("644bcbeb-dca7-4974-87fb-106daf1fba8a"),
                            Example = "хочу видеть от вас письмо",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("6e9d525b-4355-4ad0-8267-82838eb79cba"),
                            Example = "пришлите кп на мою почту",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("eff7c64c-35f2-40d6-a01c-c7431851150b"),
                            Example = "вышлите информацию на почту в письме",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("8b640529-1c8b-4b8d-bb3d-4716806acf50"),
                            Example = "вышлите кп на почту в письме",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("79369683-a294-4cec-bf33-4a50356df5d9"),
                            Example = "в письме на почту вышлите информацию",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("bd91ead9-da71-41c3-bceb-c04d49cffc7a"),
                            Example = "мне нужна информация на моем почтовом ящике",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("a8cbed0f-66ef-4c8a-a4c7-9080bda04a85"),
                            Example = "на почтовый ящик вышлите информацию",
                            ObjectionClass = "Пришлите информацию new Objection{ ObjectionClass = скайп, КП, эл.почту}"
                        },
                        new
                        {
                            Id = new Guid("57c82c44-9f74-4518-a65b-b8709da5501d"),
                            Example = "я перезвоню вам сам",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("19413c7a-c0c0-4647-8824-a253af4422e8"),
                            Example = "хочу вам позднее перезвонить",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("6dcff9cd-34ea-4660-948f-336187b12067"),
                            Example = "я вам сам наберу",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("7171c295-a317-4a0b-a686-362edee61ecf"),
                            Example = "сам наберу",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("e6492b9a-b3b0-416a-8134-a85197baf4eb"),
                            Example = "давайте я перезвоню позднее",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("c5cd8ca8-1cf9-4f4d-9cda-74047cf47a24"),
                            Example = "он вам перезвонит",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("0892f2d3-68ac-41fe-a2ed-1c97d5b34f7b"),
                            Example = "он хочет перезвонить вам позднее",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("00f88924-1c26-40ef-bdfa-b93d98efb70e"),
                            Example = "он позднее наберет вам сам",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("2340eacf-a680-4e97-aa51-c6b138cbbbc0"),
                            Example = "позднее наберу вам",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("4b810fcc-7287-4710-88cb-2f5d0d7b5a2c"),
                            Example = "позднее наберем",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("1a132a56-a41e-4d8e-acc7-29f456d9eb43"),
                            Example = "позднее наберет",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("e5ecda33-a652-44ad-9671-1a03225ef95b"),
                            Example = "наберу позже наберу потом после завтра как-нибудь потом",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("961368bb-df5e-4067-8db2-36c02d42a719"),
                            Example = "хочу позвонить вам позднее",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("168cdab2-7bf1-487e-9570-11d50cc799e3"),
                            Example = "позвоню вам потом после позднее как-нибудь",
                            ObjectionClass = "Сам перезвонит"
                        },
                        new
                        {
                            Id = new Guid("828a5248-bf22-45ad-9a78-32ef9aa62e56"),
                            Example = "у нас нет того кто этим занимается",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("5d050176-0750-4d87-b1df-590eeef995fe"),
                            Example = "у нас нет специалиста не наняли никого кто разбирается не понимаем ничего в этом этим не занимаемся не разбираемся",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("3ea0cee7-059e-456e-8402-408ca73984fb"),
                            Example = "мы это никогда не делали не понимаем как делать ничего не делали никак не знаем",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("cfb257be-d9fc-4120-a558-728695fff0da"),
                            Example = "нет человека кто этим занимается непонятно кто это будет делать",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("426467cb-6dd4-46b0-9719-9fb254dc311c"),
                            Example = "никто это делать не будет",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("cd893830-2f09-42d8-96f5-e451b8a91e1a"),
                            Example = "нет никого кто будет это делать непонятно нет специалистов",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("404060ef-f376-4d88-b481-99e4f9f13dfb"),
                            Example = "нет таких людей нет обученного персонала ",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("19bada8c-b847-4ccf-9a2d-eb79b912992b"),
                            Example = "не знаю кто будет этим заниматься",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("9d2c065f-0e96-401c-8e17-0e2bd744313b"),
                            Example = "никто не будет этим заниматься",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("5f4d1a71-e93f-4056-ae71-3d142b77f97d"),
                            Example = "некому этим заниматься никто не сможет",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("b008239f-6a39-4e11-9451-fb4e00687401"),
                            Example = "нет специалиста никакого никого знающих людей нет",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("2a73f78f-fbad-4d02-a20a-0486508782c7"),
                            Example = "некому заниматься",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("cc38f911-616c-4ab5-9bfd-5f900bdf7982"),
                            Example = "никто не будет это делать нет человека",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("3111c889-41cb-4868-9e43-c4fd9dfc6af3"),
                            Example = "не хватает специалиста по этим делам",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("340d5d85-538c-4c66-b19d-0050cdbb2cea"),
                            Example = "нет специалиста никакого",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("d669017f-ad33-42c5-9927-b7bb766fde70"),
                            Example = "некому этим заняться",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("d7636c7a-1d8e-44bf-9f6b-167b657117d2"),
                            Example = "заняться некому этим всем",
                            ObjectionClass = "Я этим не занимаюсь / У нас нет человека, кто бы этим занимался"
                        },
                        new
                        {
                            Id = new Guid("9625cb6a-85bf-4284-8c3d-6175cc80d2c2"),
                            Example = "не могу соединить вас с руководством",
                            ObjectionClass = "Не могу соединить / Запрещено соединять"
                        },
                        new
                        {
                            Id = new Guid("19f25c33-b3b8-4357-bc59-9c45c546c1ec"),
                            Example = "у нас нельзя соединять",
                            ObjectionClass = "Не могу соединить / Запрещено соединять"
                        },
                        new
                        {
                            Id = new Guid("5b681e70-0c04-4306-b1c8-1f7437d6655b"),
                            Example = "не могу вас с ним соединить прямо сейчас никак не могу вас соединить",
                            ObjectionClass = "Не могу соединить / Запрещено соединять"
                        },
                        new
                        {
                            Id = new Guid("9b2d581d-c57d-4e1f-abec-9c2efca55050"),
                            Example = "никак не могу просто никак нельзя вот так вот",
                            ObjectionClass = "Не могу соединить / Запрещено соединять"
                        },
                        new
                        {
                            Id = new Guid("b8e62b62-8ed4-4966-b437-06a9d4665795"),
                            Example = "нельзя соединять с руководством с начальством",
                            ObjectionClass = "Не могу соединить / Запрещено соединять"
                        },
                        new
                        {
                            Id = new Guid("aaaa47f7-e4dd-47a0-8a32-b03d2e98781c"),
                            Example = "мы не можем соединить вас с руководствам",
                            ObjectionClass = "Не могу соединить / Запрещено соединять"
                        },
                        new
                        {
                            Id = new Guid("8c4743c2-42a4-49b9-a092-41add76057a7"),
                            Example = "не вижу интереса в этом продукте",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("af9140f6-04fb-4291-b8d4-c0530d0637ba"),
                            Example = "не интересно",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("679daf2f-37e6-4de8-869f-44fb43d6a2f8"),
                            Example = "не вижу ничего интересного ",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("57095c0d-6130-46f4-8237-29303cac4be0"),
                            Example = "ваш продукт нам не интересен",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("feb722c3-0d6a-48a3-b046-5db090f65d68"),
                            Example = "не интересно предложение в принципе",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("6c17c7d6-2672-4eca-b252-6aaafe65204c"),
                            Example = "не понимаю, как это может быть интересно",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("c2069561-f924-481f-b490-a2b78ff1037e"),
                            Example = "мне не интересно",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("a89ce2a8-acd3-47e5-828b-471f1b8156cc"),
                            Example = "нам не интересно это изучать",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("83ad09ed-6e9f-485b-b3fe-c07d96db050d"),
                            Example = "мы не заинтересованы в этом",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("32e2acdd-b01f-497b-91cb-b5506af4c2e0"),
                            Example = "простите, не заинтересовало",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("36ca2295-4424-4d4a-adfa-c5e4ccb9ece1"),
                            Example = "не заинтересован",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("dba8600e-433e-41e3-8e4c-235b925fbd13"),
                            Example = "мы не видим в этом ничего интересного",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("323b69bd-f032-4a5f-a654-5d0f396a71c1"),
                            Example = "ничего интересного в этом не видим",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("fd78e039-0394-425a-a536-84fe278c5ddf"),
                            Example = "не видим в этом ничего интересного",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("b27359ea-f9a7-49d9-8207-158f0a4cf6ff"),
                            Example = "ваше предложение просто не интересно",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("0ccd7e2f-8d61-45e8-93b5-a28eadbd20b5"),
                            Example = "просто не интересно не нужно ",
                            ObjectionClass = "Нам это просто не интересно"
                        },
                        new
                        {
                            Id = new Guid("554f1b03-61f9-43d5-8dd0-bcd772f3089c"),
                            Example = "нам ничего не надо у нас все есть",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("a4317f98-9e8c-4085-a3ad-aaa9b3dec5bb"),
                            Example = "нам это не надо ",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("3e01e64f-2ae3-434a-a56d-a7ff7ab314d6"),
                            Example = "нам ничего не надо",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("908a74b9-7698-4ce8-a13c-284c56bf0277"),
                            Example = "нам ничего не нужно у нас все нормально",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("1a042603-81a2-43f5-ac0c-951db494b5fb"),
                            Example = "нам ничего не нужно у нас все есть",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("0ca93e9a-8100-4511-8e20-2bf1189c99d4"),
                            Example = "не надо спасибо",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("d5fbb85a-cf4a-4b57-80db-ff9076932ce0"),
                            Example = "ничего не надо",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("3b8b805b-11c6-4e94-826b-290ba913f1b6"),
                            Example = "ничего не надо все и так хорошо",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("61ae52c9-dad5-4eab-be3d-4cee548208b4"),
                            Example = "все и так хорошо ничего не надо",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("3760b9f3-1e9d-476c-9e37-5c0e2080fb1a"),
                            Example = "мы ничего не хотим",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("65e0f49a-be40-457c-a7eb-33ab48c2fb36"),
                            Example = "не хотим ничего вообще все есть",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("69cbfc72-86e5-4081-bce1-86dfde6199c0"),
                            Example = "у нас все есть ничего не надо",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("9d4983f4-8188-46a2-ba78-44311751c438"),
                            Example = "ничего нам не нужно",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("aab64ace-4182-430a-8ae7-753fcdd9c6a9"),
                            Example = "нет спасибо ничего не нужно",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("49fbb2d6-ddd0-4e24-9004-c9f0b2891eca"),
                            Example = "спасибо у нас все уже есть не надо ничего",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("4c8f1d1e-73a8-4b19-8d8c-4b761940c3a5"),
                            Example = "нет не надо ничего все есть",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("65c0fb22-a7cd-4c8f-8be5-2891b67d459a"),
                            Example = "у нас как-то все есть ничего не надо",
                            ObjectionClass = "Нам ничего не надо"
                        },
                        new
                        {
                            Id = new Guid("34577773-a12b-435d-98b1-b83d77a8527d"),
                            Example = "у нас все есть",
                            ObjectionClass = "У нас все есть"
                        },
                        new
                        {
                            Id = new Guid("b6600533-5ce4-4c60-9650-ae6ffdca904f"),
                            Example = "у нас и так все есть",
                            ObjectionClass = "У нас все есть"
                        },
                        new
                        {
                            Id = new Guid("d63431bc-8f93-4da2-a83f-bcc670308b54"),
                            Example = "у нас и так все нормально",
                            ObjectionClass = "У нас все есть"
                        },
                        new
                        {
                            Id = new Guid("f7c1f727-7ff2-4c55-b4fd-d8180a93fbbf"),
                            Example = "у нас все ок",
                            ObjectionClass = "У нас все есть"
                        },
                        new
                        {
                            Id = new Guid("efedf2bb-265c-4a67-8e6c-6f4923247ee1"),
                            Example = "все и так хорошо",
                            ObjectionClass = "У нас все есть"
                        },
                        new
                        {
                            Id = new Guid("7618d767-da42-4a38-b844-4e1a9e5079d8"),
                            Example = "и так все есть все хорошо спасибо",
                            ObjectionClass = "У нас все есть"
                        },
                        new
                        {
                            Id = new Guid("2c141bf9-2626-488e-9a28-0c63de3750c4"),
                            Example = "все хорошо ничего не надо",
                            ObjectionClass = "У нас все есть"
                        },
                        new
                        {
                            Id = new Guid("0bfa18a3-4862-4adf-a66b-46e5b1393d8a"),
                            Example = "все уже установлено все на месте",
                            ObjectionClass = "У нас все есть"
                        },
                        new
                        {
                            Id = new Guid("3a591a30-8fc5-4bc0-bef9-084f59cecf17"),
                            Example = "все есть спасибо все ок не надо ничего",
                            ObjectionClass = "У нас все есть"
                        },
                        new
                        {
                            Id = new Guid("207b5458-4434-46b3-a768-70a3c1a3e844"),
                            Example = "слишком дорого для нас",
                            ObjectionClass = "Дорого"
                        },
                        new
                        {
                            Id = new Guid("7eea0b2b-c853-4225-afff-61481c48e775"),
                            Example = "накладно для нас дорого",
                            ObjectionClass = "Дорого"
                        },
                        new
                        {
                            Id = new Guid("da7ee320-3ca0-4820-8c93-21f044180721"),
                            Example = "не потянем по цене",
                            ObjectionClass = "Дорого"
                        },
                        new
                        {
                            Id = new Guid("b49cb2cb-9923-46f4-a65e-0aed008d67f9"),
                            Example = "цена не устраивает дорого слишком",
                            ObjectionClass = "Дорого"
                        },
                        new
                        {
                            Id = new Guid("d8fd6dd9-61e7-4738-aa4d-0e5b159cd7fc"),
                            Example = "слишком большие расходы",
                            ObjectionClass = "Дорого"
                        },
                        new
                        {
                            Id = new Guid("d6f51f01-7e50-40a9-87d2-7b149a93638b"),
                            Example = "не устраивает цена",
                            ObjectionClass = "Дорого"
                        },
                        new
                        {
                            Id = new Guid("707ef6e5-5c05-4b93-afc2-8f980de3b68a"),
                            Example = "у нас нет таких денег не можем позволить себе",
                            ObjectionClass = "Дорого"
                        },
                        new
                        {
                            Id = new Guid("889981a8-6610-451a-af6f-b0d656085fe1"),
                            Example = "слишком накладно ",
                            ObjectionClass = "Дорого"
                        },
                        new
                        {
                            Id = new Guid("712471f6-618b-4729-8845-65fb16688f59"),
                            Example = "для нас это сейчас не нужно сейчас не актуально",
                            ObjectionClass = "Сейчас не актуально"
                        },
                        new
                        {
                            Id = new Guid("d02bf83c-42f9-4e9a-b92c-d18781d392a0"),
                            Example = "сейчас не подходит ",
                            ObjectionClass = "Сейчас не актуально"
                        },
                        new
                        {
                            Id = new Guid("2bdb046e-3323-4fea-a272-e47b200ccf06"),
                            Example = "сейчас другие проблемы у нас",
                            ObjectionClass = "Сейчас не актуально"
                        },
                        new
                        {
                            Id = new Guid("402f1798-4cb1-4149-ab77-26ef3bf88c85"),
                            Example = "сейчас другие задачи сейчас не в рассмотрении",
                            ObjectionClass = "Сейчас не актуально"
                        },
                        new
                        {
                            Id = new Guid("f867c705-8890-42bd-93b1-bab41d3f5a99"),
                            Example = "в данный момент не актуально",
                            ObjectionClass = "Сейчас не актуально"
                        },
                        new
                        {
                            Id = new Guid("c5bc727d-fe7a-4533-9937-e73f6cb293ea"),
                            Example = "сейчас не актуально",
                            ObjectionClass = "Сейчас не актуально"
                        },
                        new
                        {
                            Id = new Guid("d46c07ae-18ea-43c9-be41-1dc0755afa84"),
                            Example = "не актуально в данный момент",
                            ObjectionClass = "Сейчас не актуально"
                        },
                        new
                        {
                            Id = new Guid("21d9c886-8ee7-415d-ba6a-617ec17da4d8"),
                            Example = "не нужно сейчас никак не купим в данный момент",
                            ObjectionClass = "Сейчас не актуально"
                        },
                        new
                        {
                            Id = new Guid("6b0ffa06-328c-481f-bf13-f3052478564f"),
                            Example = "мне нужно подумать я подумаю ",
                            ObjectionClass = "Я подумаю/мне нужно подумать"
                        },
                        new
                        {
                            Id = new Guid("b231b971-610d-4fa6-ac42-a9ebc7256b57"),
                            Example = "отвечу позднее потом отвечу не могу сейчас ответить",
                            ObjectionClass = "Я подумаю/мне нужно подумать"
                        },
                        new
                        {
                            Id = new Guid("06944ed6-1b72-4117-96f9-877b9cf220bb"),
                            Example = "отвечу потом ",
                            ObjectionClass = "Я подумаю/мне нужно подумать"
                        },
                        new
                        {
                            Id = new Guid("80f84379-a6b0-41a3-83dc-9a6b43ce2e54"),
                            Example = "подумаю и отвечу нужно подумать нужно обмозговать",
                            ObjectionClass = "Я подумаю/мне нужно подумать"
                        },
                        new
                        {
                            Id = new Guid("b8d3983b-1e65-4d84-8f41-241b3e14bdb1"),
                            Example = "я подумаю нужно покумекать посообразить",
                            ObjectionClass = "Я подумаю/мне нужно подумать"
                        },
                        new
                        {
                            Id = new Guid("1c86a8a6-8b6d-4371-a59e-d41858486491"),
                            Example = "подумаю и отвечу потом",
                            ObjectionClass = "Я подумаю/мне нужно подумать"
                        },
                        new
                        {
                            Id = new Guid("26084a15-9df5-4db8-8b3d-9cb996ade0e7"),
                            Example = "обдумаю и отвечу обдумать думать подумать надо",
                            ObjectionClass = "Я подумаю/мне нужно подумать"
                        },
                        new
                        {
                            Id = new Guid("04f08e74-89d3-4ae7-bc92-e6ab249d1d63"),
                            Example = "пришлите подробную информацию",
                            ObjectionClass = "Пришлите КП/подробные материалы"
                        },
                        new
                        {
                            Id = new Guid("940547ba-dd38-422f-a02f-de4827a0dee9"),
                            Example = "подробные материалы вышлите инфо на почту",
                            ObjectionClass = "Пришлите КП/подробные материалы"
                        },
                        new
                        {
                            Id = new Guid("75cb7c56-6245-46e7-b229-8590ecd6d0c6"),
                            Example = "вышлите кп на почту в письме информацию ",
                            ObjectionClass = "Пришлите КП/подробные материалы"
                        },
                        new
                        {
                            Id = new Guid("d8a8fc0d-8d4f-476e-b57e-d2f136473b16"),
                            Example = "нужны подробные материалы дополнительные ",
                            ObjectionClass = "Пришлите КП/подробные материалы"
                        },
                        new
                        {
                            Id = new Guid("f0f57f66-9eb1-43b9-856b-0f681ce8fb9e"),
                            Example = "прошу вас выслать подробные материалы пришлите кп",
                            ObjectionClass = "Пришлите КП/подробные материалы"
                        },
                        new
                        {
                            Id = new Guid("ca0bda02-630d-45b4-b37e-7a6e4e81143c"),
                            Example = "у нас нет столько денег на проект нет денег",
                            ObjectionClass = "Нет денег"
                        },
                        new
                        {
                            Id = new Guid("aba37a75-2bd4-4c20-89ee-c1bf9e0db08a"),
                            Example = "высокая стоимость не потянем нет денег",
                            ObjectionClass = "Нет денег"
                        },
                        new
                        {
                            Id = new Guid("2b25c182-a203-4b7a-838e-45a0f9abe645"),
                            Example = "нет денег слишком дорого",
                            ObjectionClass = "Нет денег"
                        },
                        new
                        {
                            Id = new Guid("b5fda157-cc7b-4c71-a456-6f3710fa0a3d"),
                            Example = "оплачу позднее не готов оплатить сейчас думаю подождет",
                            ObjectionClass = "Отказ оплачивать счет"
                        },
                        new
                        {
                            Id = new Guid("bb1c1e69-331d-422a-903f-8a3f86479d5c"),
                            Example = "отказ оплачивать счет отказываюсь оплачивать счет пока",
                            ObjectionClass = "Отказ оплачивать счет"
                        },
                        new
                        {
                            Id = new Guid("c4086600-ae29-47e2-8742-26443bb6ce06"),
                            Example = "я отказываюсь оплачивать потому что",
                            ObjectionClass = "Отказ оплачивать счет"
                        },
                        new
                        {
                            Id = new Guid("56d20292-225d-431e-89eb-bb635f2bb668"),
                            Example = "оплачу потом позднее не готов",
                            ObjectionClass = "Отказ оплачивать счет"
                        },
                        new
                        {
                            Id = new Guid("559d740d-71a5-46a4-8284-e49ed67c3a44"),
                            Example = "работали с вами, не понравилось",
                            ObjectionClass = "Работали с вами, не понравилось"
                        },
                        new
                        {
                            Id = new Guid("0fc6c0f8-6237-4bf9-8ead-3af64b25c3f4"),
                            Example = "с вами работали раньше ранее не понравилось в прошлом уже было не хотим возвращаться",
                            ObjectionClass = "Работали с вами, не понравилось"
                        });
                });

            modelBuilder.Entity("ClientBarometer.Domain.Models.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ObjectionClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Processing")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("suggestion");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be2e6241-b8cc-459c-b2dd-46f7a178fbdd"),
                            ObjectionClass = "",
                            Processing = "",
                            Text = ""
                        });
                });

            modelBuilder.Entity("ClientBarometer.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70313da4-aa68-41d3-bf80-265e2743846f"),
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            Source = "Telegram",
                            SourceId = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
